parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: webdevsblog
    database_user: root
    database_password: mysql
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: a640b1009771042471001cba55c1000a6f60
