security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Webdev\AppBundle\Entity\User, property: username }
                
    encoders:
        Webdev\AppBundle\Entity\User: sha512

    firewalls:
        secured_area:
            pattern: .*
            anonymous: ~
            form_login: ~
            logout: ~
